### ISSUE TITLE
".md" files are created for tasks with Chinese name

### ISSUE THREAD

**Issue by fanshibear** [basementuniverse/vscode-kanbn#6] opened 2021-05-12 00:46 UTC
After I add a task with Chinese name, a file with empty name ".md" is created. And it prevents me from creating a second task with Chinese name because of conflicting file names.

**Comment by gordon-winkel** [comment] 2021-05-12 21:04
Hi @fanshibear, thanks for the bug report. I have reproduced the issue and it appears to be caused by the package I'm using to convert task titles into snake-case IDs (which are used in the filename).

I'm working on a fix for this and should have another release ready soon.

**Comment by fanshibear** [comment] 2021-05-13 00:37
@gordon-winkel Thanks！

**Comment by basementuniverse** [comment] 2021-05-15 23:40
Hi @fanshibear, I have released `vscode-kanbn` `0.9.2` which now has support for non-latin characters in task ids.

Please let me know if you notice any other bugs or issues :smiley: thanks!

**Closed by basementuniverse** 2021-05-15 23:40 UTC
